print("Hello World")
print('Sejam Bem-vindos ao curso de programação do Senac União da Vitória PR')
print('Olá ',"Gustavo, Alexandre")
print('Olá Gustavo')
print(5+5)
print('5'+'5')
print('Bruno' + 'Ricardo')
print(5 + 2)
print(5-2)
print(5*2)
print(5/2)
print(5**2)
print(5//2)
print(5%2)
